[package]
name = "intuitive"
version = "0.6.3"
description = "a library for building declarative text-based user interfaces"
edition = "2021"
license = "CC0-1.0"
repository = "https://github.com/enricozb/intuitive"
readme = "readme.md"

[dependencies]
crossterm = "0.25.0"
ctrlc = { version = "3.2.3", features = [ "termination" ] }
doc-cfg = "0.1"
intuitive_macros = { path = "../macros", version = "0.6.2" }
lazy_static = "1.4.0"
parking_lot = "0.12.1"
serial_test = "0.9"
thiserror = "1.0.32"
tui = "0.19.0"

[features]
unstable-doc-cfg = ["experimental"]
experimental = []

[package.metadata.docs.rs]
features = ["unstable-doc-cfg"]
