[package]
name = "intuitive_macros"
version = "0.7.0-alpha.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
proc-macro-crate = "1.2.1"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
